name: HTML/CSS/JS CI

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Build and Test
      run: npm run build && npm test

    - name: Deploy
      run: |
        # Deploy your project here
        # For example, deploying to a server using rsync
        rsync -avz --delete dist/ your-server:/var/www/html
