name: NodeJS with Gulp

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies and Build
      run: |
        npm install
        gulp

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact  # Specify the name you want for the artifact
        path: .            # Use "." to upload the entire project directory

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
